### PR TITLE
target/riscv: Set target->state in riscv013_halt_go()

### LINKED ISSUE #749: Error: [riscv.cpu0] Hart is not halted! in riscv-013 examine
Hello,

Seems after changes https://github.com/riscv/riscv-openocd/pull/743
examine function in riscv-013.c causes error message for harts with no halt on reset:

```
static int examine(struct target *target)
...
	if (!halted)
		riscv013_step_or_resume_current_hart(target, false);
```
The function riscv013_step_or_resume_current_hart prints error when target is not in HALTED state.
```
static int riscv013_step_or_resume_current_hart(struct target *target,
		bool step)
{
	if (target->state != TARGET_HALTED) {
		LOG_TARGET_ERROR(target, "Hart is not halted!");
		return ERROR_FAIL;
	}
...
```

And target->state = TARGET_HALTED is set later in deassert_reset function

I've combined old and new approaches together to overcome this issue
(and not calling riscv_is_halted every time):
```
static int riscv013_step_or_resume_current_hart(struct target *target,
		bool step)
{
	if (target->state != TARGET_HALTED && !riscv_is_halted(target)) {
		LOG_TARGET_ERROR(target, "Hart is not halted!");
		return ERROR_FAIL;
	}
...
```

Please check it out.
Log with error message is in attachment.
[ocd.log](https://github.com/riscv/riscv-openocd/files/9812566/ocd.log)

Regards,
Fedor

### PR DESCRIPTION
**Pull request by timsifive**
Then also set it when we resume in examine(), which doesn't use the full abstractions because not all required data structures are filled out yet.

Hopefully fixes #749.

Change-Id: I0c6ab16da1f035ca2fbdb9f7be1462d44ddce3a0
Signed-off-by: Tim Newsome <tim@sifive.com>

### CODE REVIEW

File: src/target/riscv/riscv-013.c [hunk 1]
```diff
@@ -1765,8 +1765,10 @@ static int examine(struct target *target)
 		return ERROR_FAIL;
 	}
 
-	if (!halted)
+	if (!halted) {
 		riscv013_step_or_resume_current_hart(target, false);
+		target->state = TARGET_RUNNING;
```
Comment (JanMatCodasip) [inline src/target/riscv/riscv-013.c:1770]: I'd recommend to set here also `target->debug_reason` - to keep the "state" and "debug_reason" in sync. (This is just for consistency. I don't think omission of this would cause any issues.)

```suggestion
		target->state = TARGET_RUNNING;
		target->debug_reason = DBG_REASON_NOTHALTED;		
```

File: src/target/riscv/riscv-013.c [hunk 2]
```diff
@@ -4331,8 +4333,17 @@ static int riscv013_halt_go(struct target *target)
 				t->state = TARGET_UNAVAILABLE;
 			}
 		}
+
```
Comment (JanMatCodasip) [inline src/target/riscv/riscv-013.c:4337]: Detail: This blank line can be removed.

```suggestion
```

**Review by JanMatCodasip — DISMISSED** [review]

File: src/target/riscv/riscv-013.c (hunk 2 above)
Comment (timsifive) [reply src/target/riscv/riscv-013.c:4337]: Yeah, but I like whitespace in some places to separate different parts of the code.

**Review by JanMatCodasip — APPROVED** [review]
